In [1]:
import numpy as np
import torch as tr


In [110]:
ntrials=3
pmtokens=4
np.concatenate([
  np.concatenate([
    np.random.permutation(np.arange(1,pmtokens+1)),
    [0]
  ])
for i in range(ntrials)])

array([1, 2, 4, 3, 0, 3, 4, 1, 2, 0, 2, 3, 1, 4, 0])

In [167]:
enc_trials_2d = np.array([
    np.random.permutation(np.arange(1,pmtokens+1)) 
    for i in range(ntrials)
])
resp_trials = np.random.randint(1,pmtokens+1,[ntrials,1])

# trials = [enc_trials_2d,resp_trials]
enc_trials_2d.shape,resp_trials.shape

trials = np.concatenate([enc_trials_2d,resp_trials],1)
tseq = np.concatenate([enc_trials_2d,np.zeros([ntrials,1])],1).astype(int)
xseq = trials.reshape(-1)
tseq = tseq.reshape(-1)

## 
print(trials)
print(tseq)

[1 2 4 3 1 2 4 1 3 1 1 3 2 4 3]
[1 2 4 3 0 2 4 1 3 0 1 3 2 4 0]
